version: '3'
services:
  test:
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - ".:/go/src/github.com/konhas/echo-server"
    command: go test -v ./...
    environment: 
      - CGO_ENABLED=0