# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: golang:1.15.6-buster

    working_directory: /go/src/github.com/konhas/echo-server
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            go clean -modcache
            go mod tidy
            go mod download
      - run:
          name: test
          command: go test -v ./... -race -coverprofile=coverage.yml -covermode=atomic
      - run: 
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
